title: Sensor Data Exchange
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sensor-data-exchange
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://sdx.sensors.gov.sg/sdx/home
google_analytics: null

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: "#00B4B4"
  logo_path: /assets/sdx-logo.png
  opendoc_logo_path: /assets/sdx-logo.png
  feedback_url: https://form.gov.sg/5e4e552386290e0013ae5685
  logo_url: https://sdx.sensors.gov.sg/sdx/home

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: 'User Guide'
    title: 'User Guide'
    subtitle: ''
    order:
      - Getting Started.md
      - Introduction.md
      - Home Page.md
      - Browse Topic.md
      - My Subscribers.md
      - My Subscriptions.md
      - Glossary.md
  - name: 'FAQs'
    title: 'FAQs'
  - name: 'Terms of Use'
    title: 'Terms of Use'
  - name: 'Privacy Statement'
    title: 'Privacy Statement'

